name: Build

env:
  NODE_VERSION: 16

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci

      - run: npm run build
