name: Upload Database

env:
  NODE_VERSION: 15

on:
  schedule:
    - cron: '0 5,17 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: yarn install --frozen-lockfile

      - run: yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
